### ISSUE TITLE
hello world stub chrome-extension

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-ext#10]
Få opp en første "hello world" chrome-extension
(og en issue vi raskt kan flytte til "Done")

**Comment by havremunken** [comment]
Sånn, nå har jeg lastet opp et skikkelig v0.0-skjelett som et utgangspunkt. 

Foreslår at vi tukler i hver våre branches til vi ser hvordan ting henger sammen, så kan vi kanskje koordinere her når vi gjør noen endringer i selve strukturen nå til å begynne med?

**Comment by havremunken** [comment]
Jeg og navn er automatisk analysis paralysis. I frykt for å ikke komme på noe perfekt, ender jeg opp med å ikke gjøre noe.

Er det teit å tenke at alt arbeid med features til selve scriptet havner i feature-blabla f.eks.?

Dette er bare starten på en tanke, fyll gjerne på med bedre idéer. 

- master - denne dilter etter og representerer ca. hvor vi er, ikke klart å lage en god stratergi i hodet ennå.
- prod-live - dette representerer tilstanden til extension som er live og ikke beta. Trigger build og deploy til Chrome web store.
- prod-beta - dette er beta extension for de som føler for det. Trigger build og deploy. Eller blir dette feil måte å gjøre det på? Hadde kanskje vært bedre med en dropdown inne i extension setttings hvor man velger hvilken man skal ha, men hvordan gjør vi *det* isåfall? Usikker. Krever mer forskning.
- feature-something - denne ser jeg for meg i all hovedsak lever lokalt på våre respektive maskiner, men vi kan selvfølgelig også dele dem på github om vi må samarbeide om enkelte ting.
- fix-issuenr - jobber på en bugfix.

Og så er det vel en god idé å tagge releases når vi pusher til deploy-trådene, f.eks. med 2018111801 som ville vært dagens første release f.eks.

Kom gjerne med bedre idéer. Mine suger sannsynligvis. :)

**Comment by larsjaas** [comment]
Kunne kanskje flyttet branch-name-scheme ting til en egen issue, og lukket denne issuen.

**Comment by havremunken** [comment]
So say we all.
