### ISSUE TITLE
tab-title rewriting

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-ext#11]
Et script jeg kjører lokalt stripper bort "RBKweb - ... - " fra tab titler fordi jeg browser rbkweb med en ny tab for hver tråd med uleste innlegg. Dermed blir tab'ene ofte veldig små, og om prefix'en ikke klippes bort så klarer jeg ikke å se hvilke tabs som er hvilke tråder.

Må være en bruker-opsjon på settings-siden.

**Comment by larsjaas** [comment]
Tenker starte med å eliminere de mest trivielle Tampermonkey-scriptene jeg kjører lokalt for rbkweb, og da er denne første kandidat.

**Comment by havremunken** [comment]
Den kan jo være en kandidat for den første milestone'n jeg opprettet, så har vi litt ekte funksjonalitet også. :)

**Comment by larsjaas** [comment]
Har to trivielle script gående (og to komplekse). Tittel-reduseringen, og farvelegge/relinke tråder med ulest innhold. Den sistnevnte tråkker litt på tærne til RFS, så regnet kanskje med at du startet i den enden. Det er i alle fall funksjonalitet som også bør inn temmelig tidlig i utviklingsløpet.

**Comment by havremunken** [comment]
Ja, helt klart, jeg er helt avhengig av dette i hverdagen, så det blir sannsynligvis den første seriøse modulen jeg legger inn.
