### ISSUE TITLE
Gitter chatroom for RBKweb-ext

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-ext#30]
Prøvde å sette opp ett, men knoter med at Gitter ikke får lest inn repo-listen for RosenborgSupporterSoftware e.l, og fant ikke løsningen iblant settingene umiddelbart. Om f.eks. @havremunken vet hvordan så kunne han satt det opp, og lukket tasken :)

**Comment by havremunken** [comment]
Tror jeg fikk det til nå - vet ikke hvorfor du ikke fikk det til, kanskje jeg står som "eier" av repo eller noe? Du skal ha blitt invitert ihvertfall. :)

**Comment by larsjaas** [comment]
Stod noe om at owner måtte åpne for det, men trodde jeg var owner, men kanskje bare medlem av gruppen owners som er ikke er superbruker men duperbruker.
