### ISSUE TITLE
ukedag i kampoversikt

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-ext#40]
Vise ukedag i kampoversikten på rbkweb.
Kan i tillegg farvelegge seier/uavgjort/tap, og utheve kommende kamp.

**Comment by havremunken** [comment]
Tanke: Er URL'ene til 2mas konsekvente her? Denne delen av RBKweb byttes vel ikke automatisk ut ifm. nytt forum. Kanskje en anledning til å være sikre på at URLene for de forskjellige sesongene blir "standardiserte" hvis de ikke allerede er det.

Er ikke helt sikker på om det er noe problem, bare husker dette var en ting jeg har hatt i hodet på et tidspunkt, sannsynligvis når Eru lagde det opprinnelige scriptet og vi begynte å tukle med det.

**Comment by larsjaas** [comment]
Om du tenker på identifisering, samt å dra ut årstallet så har jeg det klart - bortsett fra at jeg ignorerer 99-sesongen.

**Comment by larsjaas** [comment]
Denne er "Done"/ferdig, uten integrering i modul-systemet (som akkurat nå ikke bygger).
